name: sport_app
description: SportBooking
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.1
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3

  # ===
  fpdart: ^1.1.0
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.2.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  graphql_flutter: ^5.2.0-beta.5
  jwt_decode: ^0.3.1
  file_picker: ^6.1.1
  http: ^1.1.0
  google_sign_in: ^6.2.1
  webview_flutter: ^4.5.0
  url_launcher: ^6.2.5
  uuid: ^4.4.0
  crypto: ^3.0.3
  google_maps_flutter: ^2.5.3
  google_maps_cluster_manager: ^3.1.0
  google_maps_flutter_platform_interface: 2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  freezed: ^2.4.3
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/image/
    - assets/svg/icons/
