name: sport_app
description: SportBooking
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^11.1.2
  flutter_svg: ^2.0.7
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.1
  google_fonts: ^6.1.0
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/svg/
